/* MF-02 local view/controller. No authentication, network or Provider calls. */
'use strict';
const M=globalThis.MF, KEY='museflow-mf02-v1';
let state;try{state=JSON.parse(sessionStorage.getItem(KEY));}catch{}if(!state||state.schema!==1)state=M.seed(M.fresh());
let authAttempt=0;
let page=state.page||'workspace',detailId=null,ledgerTask=null,adminRole=false,authMode='login',busy=false,modalReturn=null;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={workspace:'创作工作区',library:'作品库',inspiration:'灵感推荐',credits:'积分与用量',admin:'管理后台'};
const currency=c=>c==='creation'?'创作积分':'语音积分';
const getAsset=id=>state.assets.find(a=>a.id===id&&M.accessible(a));
const blocked=()=>['loading','network','interrupted'].includes(state.scenario);
const current=()=>state.conversations.find(c=>c.id===state.active);
const activeTask=()=>state.tasks.find(t=>t.id===current()?.taskIds.at(-1));
const button=(text,action,cls='',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const badge=(text,cls='')=>`<span class="badge ${cls}">${text}</span>`;
function save(){state.page=page;try{sessionStorage.setItem(KEY,JSON.stringify(state));}catch{notify('浏览器存储不可用：仅保留在内存，刷新会丢失。');}}
let toast;function notify(text){$('#notice').textContent=text;clearTimeout(toast);toast=setTimeout(()=>$('#notice').textContent='',6000);}
function go(p){page=p;detailId=null;history.replaceState(null,'','#'+p);save();render();$('#main')?.scrollTo(0,0);$('#main')?.focus({preventScroll:true});}
function waveform(){return `<span class="waveform" aria-hidden="true">${[32,54,76,44,88,62,36,70,52,84,46,66,38,58].map(h=>`<i style="height:${h}%"></i>`).join('')}</span>`;}
function media(title='演示音阶'){return `<div class="audio-preview">${waveform()}<div><strong>${esc(title)}</strong><p class="hint">自制 8 秒合成音阶 · 非本次 AI 生成 · 非 TTS 人声</p></div><audio controls preload="metadata" aria-label="试听 ${esc(title)}"><source src="assets/sample.wav" type="audio/wav">浏览器不支持音频，可下载测试素材。</audio></div>`;}
function auth(){const modeIcon=authMode==='login'?`<button type="button" class="auth-mode-icon" data-action="auth-register" aria-label="注册账号"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 19a6 6 0 0 0-12 0M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M19 8v6M16 11h6"/></svg><span>注册</span></button>`:`<button type="button" class="auth-mode-icon" data-action="auth-login" aria-label="返回登录"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg><span>返回登录</span></button>`;return `<main id="main" tabindex="-1" class="auth"><section class="auth-art"><div class="brand"><b>∿</b>MuseFlow</div><div><p class="eyebrow">A SPACE FOR YOUR SOUND</p><h1>让一个想法，<br>慢慢成为音乐。</h1><p class="muted">从第一句歌词，到下一段旋律。<br>你的创作，由你确认每一步。</p></div><img src="assets/cover.svg" alt="自制紫色波纹与微光插画"><p class="hint">P0 交互原型 · 歌词 / 音乐 / 语音</p></section><section class="auth-form"><div class="auth-form-inner"><div class="auth-form-head"><p class="eyebrow">${authMode==='login'?'欢迎登录':'创建账号'}</p>${modeIcon}</div><h2>${authMode==='login'?'欢迎回来':'创建你的创作空间'}</h2><p class="muted">${authMode==='login'?'登录后继续音乐创作。':'注册后开始保存你的灵感与作品。'}</p><form id="auth-form" novalidate>${authMode==='register'?'<div><label for="nickname">昵称</label><input id="nickname" maxlength="30" value="创作者" autocomplete="nickname" aria-describedby="auth-error" required></div>':''}<div><label for="email">邮箱</label><input id="email" type="email" value="creator@example.test" autocomplete="email" aria-describedby="auth-error" required></div><div><label for="pass">密码</label><input id="pass" type="password" value="demo-only" autocomplete="current-password" aria-describedby="password-help auth-error" required><small id="password-help">当前为本地演示，输入内容不会发送或保存。</small></div><p id="auth-error" class="error" role="alert"></p><button class="primary auth-submit" type="submit">${authMode==='login'?'进入工作区 →':'创建工作区 →'}</button><p class="hint">本标签页仅保存演示创作数据；关闭页面不会发出取消任务请求。</p></form></div></section></main>`;}
const scenarios={normal:'正常完整流程',empty:'空会话',loading:'加载历史',confirm:'等待确认',insufficient:'余额不足',expired:'报价过期',queued:'排队中',running:'运行中',succeeded:'成功交付',failed:'明确失败',cancel_requested:'取消处理中',canceled:'已取消',unsupported:'运行中不支持取消',reconciling:'结果未知 / 长期冻结',interrupted:'消息中断',network:'网络异常',real:'真实来源样式示例'};
function shell(){return `<div class="shell"><aside class="sidebar"><div class="brand"><b>∿</b>MuseFlow</div><div><p class="eyebrow">你的创作空间</p><nav class="nav" aria-label="主要导航">${Object.entries(names).filter(([k])=>k!=='admin').map(([k,v],i)=>`<a href="#${k}" ${page===k?'aria-current="page"':''}><span>${['✧','▤','◈','◉','⚙'][i]}</span>${v}</a>`).join('')}</nav></div><div class="sidebar-foot">${badge('P0 · 原型预览')}<p class="hint">翻唱与声音克隆：P1<br>尚未开放</p><p class="hint">所有数值均为演示提案</p></div></aside><div><header class="topbar"><div><strong>个人工作空间</strong>${!state.admin.userEnabled?badge('演示账户已停用，不能新建任务','bad'):''}<small>独立创作，一步一步来</small></div><div class="row">${badge('Mock · 模拟演示')}<span>创作 ${state.wallets.creation.available} / 语音 ${state.wallets.voice.available}</span>${button('退出','logout')}</div></header><details class="scenario-panel"><summary>演示场景 · 原型辅助功能</summary><div class="row"><label for="scenario">状态快照</label><select id="scenario">${Object.entries(scenarios).map(([k,v])=>`<option value="${k}" ${state.scenario===k?'selected':''}>${v}</option>`).join('')}</select>${button('载入场景','scenario')}${button('重置全部演示数据','reset','danger')}${button('查看管理后台演示','admin-demo')}</div><p class="hint">载入场景会重置本标签页演示数据。场景保持静止，通过「推进模拟任务」观察变化；不会请求服务。</p></details><main id="main" tabindex="-1" class="content"><div class="page-heading"><div><p class="eyebrow">${{workspace:'CREATE SOMETHING YOURS',library:'YOUR CREATIVE COLLECTION',inspiration:'A LITTLE SPARK',credits:'CLEAR AT EVERY STEP',admin:'DEMO OPERATIONS'}[page]}</p><h1>${names[page]}</h1><p class="muted">${{workspace:'把灵感交给对话，把每一次决定留给你。',library:'每一个版本，都值得被好好保留。',inspiration:'从一个标签，找到下一段旋律的起点。',credits:'可用、冻结与已结算，每一笔都清楚。',admin:'脱敏概况与操作演示，不代表真实权限控制。'}[page]}</p></div>${page==='workspace'?button('＋ 新建会话','new'):page==='library'?button('开始创作','create','primary'):''}</div>${({workspace,library,inspiration,credits,admin}[page])()}</main></div></div>`;}
// Preserve the exact control identity when a list is reordered or a modal closes.
function focusIdentity(element) {
  return element ? {id:element.id,action:element.dataset?.action,item:element.dataset?.id,href:element.getAttribute?.('href')} : null;
}
function restoreFocus(identity) {
  if(!identity)return;
  let element=identity.id ? document.getElementById(identity.id) : null;
  if(!element&&identity.action)element=[...document.querySelectorAll('[data-action]')].find(e=>e.dataset.action===identity.action&&e.dataset.id===identity.item);
  if(!element&&identity.href)element=[...document.querySelectorAll('a[href]')].find(e=>e.getAttribute('href')===identity.href);
  (element||$('#main'))?.focus({preventScroll:true});
}
function render() {
  if(state.logged)history.replaceState(null,'','#'+page);
  const focus=focusIdentity(document.activeElement);
  const scrollTop=$('#main')?.scrollTop||0;
  const scenarioOpen=$('.scenario-panel')?.open||false;
  $('#app').innerHTML=state.logged?shell():auth();
  if($('.scenario-panel'))$('.scenario-panel').open=scenarioOpen;
  if($('#main'))$('#main').scrollTop=scrollTop;
  if(!$('#modal').open)restoreFocus(focus);
}
function clarificationCard(c) {
  const d=c.parameterDraft||{text:c.intent,language:'中文',style:'轻音乐'};
  return `<form id="clarify" class="card proposal"><h3>先补充几个创作参数</h3><p class="muted">${c.tool==='speech.synthesize'?'使用演示预置音色 demo:soft；这里仅有音阶样例，没有人声合成。':'确认语言、风格和内容；修改后需重新报价。'}</p><label for="parameter-text">创作内容 / 文本</label><textarea id="parameter-text" maxlength="5000" required aria-describedby="parameter-error">${esc(d.text)}</textarea><div class="fields"><div><label for="language">语言</label><select id="language">${['中文','英文'].map(v=>`<option ${d.language===v?'selected':''}>${v}</option>`).join('')}</select></div>${c.tool!=='speech.synthesize'?`<div><label for="style">风格</label><select id="style">${['轻音乐','流行','氛围'].map(v=>`<option ${d.style===v?'selected':''}>${v}</option>`).join('')}</select></div>`:''}</div><p id="parameter-error" class="error" role="alert"></p><button class="primary section-gap" type="submit">查看工具和参数提议</button></form>`;
}
function proposalCard(c){const p=c.proposal;if(!p||c.clarifying)return '';const t=M.tools[p.tool],language=p.input.language||'中文',style=p.input.style||p.input.specificationId||'轻音乐';return `<section class="card proposal"><div class="row spread"><div><p class="eyebrow">AGENT PROPOSAL</p><h3>工具与参数提议</h3></div>${badge(state.tasks.some(t=>t.toolCallId===p.id)?'已确认':'未执行')}</div><div class="parameter-summary"><div class="tool-orb" aria-hidden="true">${p.tool==='lyrics.generate'?'✦':p.tool==='music.generate'?'♫':'◉'}</div><div><strong>${t.label}</strong><code>${p.tool}</code></div><div class="parameter-chips">${badge(language)}${badge(style)}${p.input.lyricsAssetId?badge('引用歌词版本'):''}${p.input.voiceRef?badge('预置音色'):''}</div></div><div class="proposal-copy"><small>创作内容</small><p>${esc(p.input.theme||p.input.prompt||p.input.text)}</p></div>${p.input.lyricsAssetId?`<p class="task-meta">引用歌词版本：${esc(p.input.lyricsAssetId)}</p>`:''}${p.input.voiceRef?`<p class="task-meta">演示允许音色：${esc(p.input.voiceRef)}（无真实人声样本）</p>`:''}<p class="hint">规格来自模拟能力表；Agent 提议不会触发执行。${p.retryOfTaskId?'重新尝试关联原任务 '+esc(p.retryOfTaskId):''}</p>${!c.quote?`<div class="row section-gap">${button('获取本步报价','quote','primary')}${button('修改参数','edit-proposal')}</div>`:''}</section>`;}
function quoteCard(c){const q=c.quote;if(!q||state.tasks.some(t=>t.quoteId===q.id))return '';const missing=c.proposal.input.lyricsAssetId&&!getAsset(c.proposal.input.lyricsAssetId);const expired=Date.parse(q.expiresAt)<=Date.now(),poor=BigInt(state.wallets[q.currency].available)<BigInt(q.amount),blocked=!state.admin.userEnabled||!state.admin.toolEnabled;const blockReason=!state.admin.userEnabled?'账户已停用，不能确认新任务。':'工具已暂停，不能确认新任务。';return `<section class="card section-gap" aria-label="报价确认"><div class="row spread"><h3>确认这一小步</h3>${badge(expired?'报价已过期':'等待明确确认',expired?'warn':'')}</div><div class="quote-amount">${q.amount} <small>${currency(q.currency)}</small></div><p>可用 ${state.wallets[q.currency].available} · 当前冻结 ${state.wallets[q.currency].held}</p><p class="hint">币种 ${q.currency} · ${q.priceVersion} · 演示价格<br>有效至 ${new Date(q.expiresAt).toLocaleString('zh-CN')}（本地时间）</p><p>确认后先冻结，成功交付后结算；失败或成功取消后释放。</p>${missing?'<p class="error" role="alert">引用歌词已删除，不能执行此报价。请新建创作并重新选择输入。</p>':''}${poor?'<p class="error" role="alert">余额不足：请调整参数或联系演示管理员。不会创建任务。</p>':''}${blocked?`<p class="error" role="alert">${blockReason}</p>`:''}${expired&&!missing?'<p class="error">QUOTE_EXPIRED：旧报价不可执行，需重新报价并确认。</p>':''}<div class="row">${missing?button('新建创作，重新选择输入','create','primary'):expired?button('重新获取报价','quote','primary'):button('确认并冻结 '+q.amount+' 积分','confirm','primary',poor||blocked?'disabled':'')}${missing?'':button('修改参数，作废报价','edit-proposal')}</div></section>`;}
function taskCard(t){if(!t)return '';const fund={held:'冻结中 · 尚未扣除',captured:'已结算 · 已扣除',released:'已释放 · 退回可用'}[t.reservation.state];return `<section class="card section-gap" aria-label="任务状态"><div class="row spread"><h3>${M.statuses[t.status][0]}</h3>${badge(t.sourceMode==='real'?'真实来源 · 仅样式示例':'Mock 模拟任务',t.status==='succeeded'?'good':t.status==='failed'?'bad':'warn')}</div><p>${{queued:'任务已受理，等待执行。关闭页面不等于取消。',running:'正在处理本步任务；这里没有真实 Provider 调用。',reconciling:'外部结果尚不确定，正在核对原请求。保持冻结，不能再次付费提交。',cancel_requested:'取消不保证成功。收到明确取消结果前保持冻结。',succeeded:'演示素材已归档到作品库。不是本次真实生成结果。',failed:'已确认终止且无可交付结果。重新报价并确认后才会创建新任务。',canceled:'已确认取消，冻结额度已释放。'}[t.status]}</p>${t.error?`<p class="error" role="alert">${esc(t.error.code)}：${esc(t.error.message)}</p>`:''}<div class="steps">${['queued','running','succeeded'].map(k=>`<span class="${t.status===k?'active':''}">${M.statuses[k][0]}</span>`).join('')}</div><strong>${currency(t.reservation.currency)} ${t.reservation.amount} · ${fund}</strong><p class="task-meta">taskId: ${t.id}<br>价格版本：${esc(t.priceVersion)} · 权益版本：${esc(t.planVersion||'未记录')}</p><div class="row">${t.allowedActions.includes('cancel')?button('请求取消','cancel'):''}${t.allowedActions.includes('requote')?button('重新报价','requote'):''}${t.allowedActions.includes('view_result')?button('查看结果','result','primary',getAsset(t.assetIds[0])?'':'disabled'):''}${button('查询原任务','query')}${button('关联积分流水','task-ledger')}</div>${['queued','running','cancel_requested'].includes(t.status)?`<hr><p class="hint">原型辅助：手动推进，不表示服务端操作权限。</p>${button('推进模拟任务','advance')}`:''}${t.status==='reconciling'?'<p class="hint">下一步：等待原请求查询或管理员依据证据核对。没有再次付费入口。</p>':''}${t.status==='succeeded'?resultInline(t):''}</section>`;}
function resultInline(t){const a=getAsset(t.assetIds[0]);if(!a)return '<p class="hint">关联作品已删除；任务与账本证据仍保留。</p>';return `<div class="section-gap"><h3>${esc(a.title)}</h3>${a.kind==='lyrics'?`<pre>${esc(a.textContent)}</pre>`:media(a.title,a.id)}<div class="row">${button('下载样例','download','',`data-id="${a.id}"`)}${a.kind==='lyrics'?button('以此歌词继续生成音乐','next-music','',`data-id="${a.id}"`):''}</div></div>`;}
function sessionRail(t,c){const status=t?M.statuses[t.status][0]:c.quote?'等待确认':c.proposal?'等待报价':c.clarifying?'补充参数':'等待意图',tone=t?.status==='succeeded'?'good':t?.status==='failed'?'bad':t?'warn':'';return `<section class="card session-rail"><div class="row spread"><div><p class="eyebrow">LIVE SESSION</p><h3>当前创作状态</h3></div>${badge(status,tone)}</div>${t?`<div class="rail-task"><div class="row spread"><strong>${M.tools[t.tool].label}</strong><span>${currency(t.reservation.currency)} ${t.reservation.amount}</span></div><div class="progress"><span style="width:${t.status==='queued'?'24':t.status==='running'||t.status==='cancel_requested'||t.status==='reconciling'?'62':'100'}%"></span></div><p>${{queued:'任务已进入队列，可在派发前取消。',running:'生成处理中，页面关闭不会取消任务。',cancel_requested:'正在等待明确取消结果。',reconciling:'结果未知，继续保留冻结额度。',succeeded:'作品已归档，可以试听和下载。',failed:'本次未交付，冻结额度已经释放。',canceled:'任务已取消，冻结额度已经释放。'}[t.status]}</p><p class="task-meta">${t.id}</p></div>`:`<div class="rail-empty"><span aria-hidden="true">${c.proposal?'♫':'✦'}</span><p>${c.quote?'报价已准备，请回到对话区明确确认。':c.proposal?'参数提议已准备，下一步获取报价。':c.clarifying?'正在补充创作参数，尚未执行工具。':'描述一个想法，助手会先澄清参数。'}</p></div>`}<hr><p class="eyebrow">YOUR TOOLKIT</p><div class="tool-list"><span>✦ 歌词生成 ${badge('Mock')}</span><span>♫ 音乐生成 ${badge('Mock')}</span><span>◉ 语音合成 ${badge('Mock')}</span></div><p class="muted">翻唱 / 声音克隆 ${badge('P1 未开放')}</p><p class="hint">音色、时长与价格由服务端能力表返回；当前均为演示提案。</p></section>`;}
function workspace(){const c=current(),t=activeTask();return `<div class="workspace"><section class="card conversation"><div class="row spread"><h2>${esc(c.title)}</h2>${badge('创作助手')}</div><p class="hint">每个收费步骤单独报价和确认。恢复时读取会话历史并查询原 taskId。</p>${state.scenario==='loading'?`<div class="empty" role="status"><div class="empty-symbol">◌</div><h3>正在加载会话历史…</h3>${button('完成模拟加载','recover')}</div>`:''}${['network','interrupted'].includes(state.scenario)?`<div class="notice-inline" role="alert">${state.scenario==='network'?'网络异常不代表生成失败。':'消息 interrupted：未完成的参数不可执行。'} 保留草稿及原任务，恢复后先查询。${button('恢复历史并查询原任务','recover')}</div>`:''}${state.scenario!=='loading'&&!c.messages.length&&!c.proposal?`<div class="empty"><div class="empty-symbol">✧</div><h2>今天，想创造什么声音？</h2><p class="muted">一段歌词、一首音乐，或一句温柔的问候。</p><div class="row" style="justify-content:center">${button('写一首晚风的歌','example-lyrics')}${button('生成一段轻音乐','example-music')}${button('把文字读出来','example-tts')}</div></div>`:''}${c.messages.map(m=>`<div class="message ${m.role==='user'?'user':''}">${m.role!=='user'?'<div class="agent-label">✧ MuseFlow 助手 · 模拟回复</div>':''}<div>${esc(m.text)}</div></div>`).join('')}${c.clarifying?clarificationCard(c):''}${proposalCard(c)}${quoteCard(c)}${taskCard(t)}<form id="intent-form" class="composer"><label for="intent">描述你的创作意图</label><textarea id="intent" placeholder="例如：写一首关于晚风与归途的中文歌…" maxlength="1000" required>${esc(c.draft||'')}</textarea><div class="row spread"><small>仅模拟澄清，不调用大模型</small><button class="primary" type="submit" ${t?.reservation.state==='held'||state.scenario==='loading'?'disabled':''}>发送意图 ↑</button></div></form></section><aside class="context"><section class="card"><p class="eyebrow">CONVERSATIONS</p><h3>创作会话</h3>${state.conversations.map(x=>button(esc(x.title),'conversation','list-button',`data-id="${x.id}" ${x.id===state.active?'aria-current="true"':''}`)).join('')}</section>${sessionRail(t,c)}</aside></div>`;}
let filters={q:'',kind:'',tag:'',from:'',to:'',status:'accessible'},ledgerCurrency='';
function library(){
 if(detailId)return assetDetail();
 const list=state.assets.filter(a=>(!filters.q||(a.title+' '+(a.textContent||'')).includes(filters.q))
  &&(!filters.kind||a.kind===filters.kind)&&(!filters.tag||a.tags.includes(filters.tag))
  &&(!filters.from||localDate(a.createdAt)>=filters.from)&&(!filters.to||localDate(a.createdAt)<=filters.to)
  &&(!filters.status||(filters.status==='accessible'?M.accessible(a):a.status==='deletion_pending')));
 return `<form id="filters" class="filter"><div><label for="search">搜索标题或歌词</label><input id="search" value="${esc(filters.q)}" placeholder="输入关键词"></div><div><label for="kind">作品类型</label><select id="kind"><option value="">全部类型</option>${['lyrics','audio','cover'].map((k,i)=>`<option value="${k}" ${filters.kind===k?'selected':''}>${['歌词','音频','封面'][i]}</option>`).join('')}</select></div><div><label for="tag">风格</label><select id="tag"><option value="">全部风格</option>${['轻音乐','流行','氛围'].map(v=>`<option ${filters.tag===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label for="asset-status">访问状态</label><select id="asset-status"><option value="accessible" ${filters.status==='accessible'?'selected':''}>可访问</option><option value="deletion_pending" ${filters.status==='deletion_pending'?'selected':''}>删除处理中</option><option value="" ${!filters.status?'selected':''}>全部（含删除回执）</option></select></div><div><label for="from">起始日期</label><input id="from" type="date" value="${filters.from}"></div><div><label for="to">结束日期</label><input id="to" type="date" value="${filters.to}"></div><p id="filter-error" class="error" role="alert"></p><div class="row"><button type="submit">应用筛选</button>${button('清空筛选','clear-filter')}</div></form><p class="hint">${list.length} 条记录 · 可访问是 UI 筛选，不新增后端状态；删除回执不含作品正文，不能预览或下载。</p><div class="grid section-gap">${list.map(a=>`<article class="card asset-card">${!M.accessible(a)?'<div class="art art-green" aria-hidden="true">—</div>':a.kind==='cover'?'<img class="cover" src="assets/cover.svg" alt="微光原创封面">':a.kind==='audio'?`<div class="track-art">${waveform()}<span>00:08</span></div>`:`<div class="art art-peach" aria-hidden="true">Aa</div>`}<div class="row">${badge(a.kind==='lyrics'?'歌词':a.kind==='audio'?'音频':'封面')}${badge(!M.accessible(a)?'deletion_pending':a.sourceMode==='manual'?'人工 / 自制':'Mock 样例')}</div><h2 class="asset-title">${esc(a.title)}</h2><p class="muted">${a.tags.join(' · ')} · v${a.version}</p>${M.accessible(a)?button('查看作品','detail','',`data-id="${a.id}"`):`<p>访问已撤销。仅保留本地删除回执，不代表服务器已清理。</p>${button('模拟完成清理','finish-delete','',`data-id="${a.id}"`)}`}</article>`).join('')}</div>${!list.length?`<div class="card empty"><h2>还没有符合条件的作品</h2><p>调整筛选，或从一个新灵感开始。</p>${button('开始创作','create','primary')}</div>`:''}`;
}
function localDate(value){const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function assetDetail(){const a=getAsset(detailId);if(!a){detailId=null;return library();}return `<div class="row">${button('← 返回作品库','back-library')}${badge(a.sourceMode==='manual'?'manual · 人工版本 / 自制素材':'mock · 模拟产物')}</div><div class="grid two section-gap"><section class="card"><h2>${esc(a.title)}</h2>${a.kind==='lyrics'?`<pre>${esc(a.textContent)}</pre>`:a.kind==='cover'?'<img class="cover" src="assets/cover.svg" alt="原创微光封面">':media(a.title,a.id)}<div class="row">${button('下载样例','download','primary',`data-id="${a.id}"`)}${button('重命名','rename','',`data-id="${a.id}"`)}${button('删除作品','delete','danger',`data-id="${a.id}"`)}</div></section><section class="card"><h3>版本与来源</h3><p>v${a.version} · ${new Date(a.createdAt).toLocaleString('zh-CN')}</p><p>来源：${a.sourceMode==='manual'?'人工编辑或仓库自制':'本地固定样例，非本次真实生成'}</p><p class="task-meta">关联任务：${a.taskId||'无（自制素材）'}<br>父版本：${a.parentAssetId||'无'}<br>引用歌词：${a.lyricsAssetId||'无'}</p>${a.taskId?`<div class="row">${button('查看原会话','asset-conversation','',`data-id="${a.id}"`)}${button('查看关联流水','asset-ledger','',`data-id="${a.id}"`)}</div>`:''}${a.kind==='lyrics'?`<hr><h3>继续打磨这段歌词</h3><p>人工编辑免费保存新版本。AI 改写需新任务及单独报价；两者都不会改变已有音频。</p><div class="row">${button('人工编辑新版本','manual','',`data-id="${a.id}"`)}${button('AI 改写提议','rewrite','',`data-id="${a.id}"`)}${button('用此版本生成音乐','next-music','',`data-id="${a.id}"`)}</div>`:''}</section></div>`;}
const inspirations=[{id:'wind',title:'晚风里的留白',tag:'轻音乐',text:'以晚风和归途为主题，创作一段温暖而克制的音乐。',art:'art-violet'},{id:'city',title:'城市醒来之前',tag:'氛围',text:'用清晨的街道与微光，展开一段缓慢的氛围音乐。',art:'art-green'},{id:'letter',title:'寄给明天的信',tag:'流行',text:'写一首关于重新出发的中文流行歌词。',art:'art-peach'}];
function inspiration(){const p=state.preferences;const list=inspirations.filter(i=>!p.enabled||!p.hidden.includes(i.id)).sort((a,b)=>p.enabled?Number(p.saved.includes(b.id)||p.tags.includes(b.tag))-Number(p.saved.includes(a.id)||p.tags.includes(a.tag)):0);return `<section class="card"><div class="row spread"><div><h3>你的灵感偏好</h3><p class="muted">${p.tags.length?'已选择：'+p.tags.join('、'):'暂无历史偏好，从通用标签开始。'}</p></div><div class="row"><label class="check"><input id="personalization" type="checkbox" ${p.enabled?'checked':''}>开启个性化</label>${button('重置偏好','reset-preferences')}</div></div><div class="row">${['轻音乐','氛围','流行'].map(t=>button(t,'preference',p.tags.includes(t)?'primary':'',`data-id="${t}"`)).join('')}</div><p class="hint">演示排序：收藏 / 选中标签优先，不感兴趣隐藏。关闭后停止记录推荐反馈并展示通用候选；重置清除偏好，不删除作品与账本。</p></section><div class="grid section-gap">${list.map(i=>`<article class="card"><div class="art ${i.art}" aria-hidden="true">∿</div>${badge(i.tag)}<h2 class="asset-title">${i.title}</h2><p>${i.text}</p><p class="hint">推荐理由：${p.enabled&&(p.tags.includes(i.tag)||p.saved.includes(i.id))?'与你的演示标签或收藏匹配':'通用编辑灵感，无历史也可探索'}</p>${media(i.title)}<div class="row">${button(p.saved.includes(i.id)?'已收藏':'收藏','favorite','',`data-id="${i.id}" ${!p.enabled?'disabled':''}`)}${button('不感兴趣','dislike','',`data-id="${i.id}" ${!p.enabled?'disabled':''}`)}${button('用作创作起点','use-inspiration','',`data-id="${i.id}"`)}</div></article>`).join('')}</div>${!list.length?'<p class="empty">候选已全部隐藏，重置偏好可恢复通用灵感。</p>':''}`;}
function credits(){const entries=state.entries.filter(e=>(!ledgerTask||e.taskId===ledgerTask)&&(!ledgerCurrency||e.currency===ledgerCurrency)).slice().reverse();return `<div class="grid two">${Object.entries(state.wallets).map(([k,w])=>`<section class="card"><div class="row spread"><h2>${currency(k)}</h2>${badge(k+' · 名称提案')}</div><p class="muted">可用余额</p><div class="stat">${w.available}<small> 积分</small></div><p>冻结中 <strong>${w.held}</strong> · 不等于已扣除</p><p class="hint">${k==='creation'?'歌词、音乐':'TTS'} · 不互换、不抵扣</p></section>`).join('')}</div><section class="card section-gap"><div class="row spread"><h2>基础演示方案 ${badge('权益 v'+state.admin.planVersion)}</h2><span class="muted">价格、额度及限制均待团队确认</span></div><p>允许歌词 / 音乐 / TTS；固定演示音频规格 8 秒；并发 1；不提供支付入口。</p><p>已创建 ${state.tasks.length} 次任务 · 已交付 ${state.tasks.filter(t=>t.status==='succeeded').length} 次 · 创作已结算 ${sumCaptured('creation')} · 语音已结算 ${sumCaptured('voice')}</p><details><summary>查看使用记录（${state.tasks.length} 条）</summary>${state.tasks.map(t=>`<p>${M.tools[t.tool].label} · ${M.statuses[t.status][0]} · ${currency(t.reservation.currency)} ${t.reservation.amount}<br><code>${t.id}</code> · ${new Date(t.createdAt).toLocaleString('zh-CN')}</p>`).join('')||'<p>暂无使用记录。</p>'}</details></section><section class="card section-gap"><div class="row spread"><h2>积分流水</h2>${ledgerTask?button('查看全部流水','all-ledger'):badge('演示账本')}</div>${ledgerTask?`<p class="task-meta">关联任务 ${ledgerTask}</p>`:''}<label for="ledger-currency">流水币种</label><select id="ledger-currency"><option value="">两种积分</option><option value="creation" ${ledgerCurrency==='creation'?'selected':''}>创作积分</option><option value="voice" ${ledgerCurrency==='voice'?'selected':''}>语音积分</option></select><div class="ledger"><table><thead><tr><th>动作 / 币种</th><th>可用变化</th><th>冻结变化</th><th>任务 / 说明</th></tr></thead><tbody>${entries.map(e=>`<tr><td>${{grant:'初始发放',reserve:'冻结',capture:'结算',release:'释放',adjustment:'管理员调整'}[e.kind]}<br><small>${currency(e.currency)}</small></td><td>${e.availableDelta}</td><td>${e.heldDelta}</td><td>${e.taskId?`<code>${e.taskId}</code><br>`:''}${esc(e.reason)}<br><small>${new Date(e.createdAt).toLocaleString('zh-CN')}</small></td></tr>`).join('')}</tbody></table></div>${!entries.length?'<p class="empty">暂无关联流水</p>':''}</section>`;}
function sumCaptured(c){return state.entries.filter(e=>e.currency===c&&e.kind==='capture').reduce((a,e)=>a-BigInt(e.heldDelta),0n).toString();}
function admin(){return `<section class="notice-inline"><div class="row spread"><span>当前演示角色：${adminRole?'管理员':'创作者'}。角色切换仅控制原型展示，不是权限验证。</span>${button(adminRole?'切回创作者':'切换演示管理员','role')}</div></section>${!adminRole?'<section class="card empty"><h2>后台权限说明</h2><p>正式产品普通用户应收到 403，由服务端执行权限与归属校验。</p></section>':`<div class="grid two"><section class="card"><h3>用户与额度</h3><p>虚构账户 creator@example.test ${badge(state.admin.userEnabled?'启用':'停用',state.admin.userEnabled?'good':'bad')}</p><div class="row">${button(state.admin.userEnabled?'停用演示用户':'启用演示用户','admin-user')}${button('调整演示额度','admin-credit')}</div></section><section class="card"><h3>工具可用性</h3><p>歌词 / 音乐 / TTS ${badge(state.admin.toolEnabled?'Mock 可用':'已停用')}</p>${button(state.admin.toolEnabled?'停用演示工具':'启用演示工具','admin-tool')}<p class="hint">无真实 Provider 配置与密钥。P1 工具未开放。</p></section><section class="card"><h3>价格版本</h3><p>demo-price-${state.admin.priceVersion} · 歌词 8 / 音乐 24 / TTS 6</p>${button('发布下一演示版本','admin-price')}<p class="hint">发布采用相同样例金额；历史报价与任务快照不覆盖。</p></section><section class="card"><h3>权益版本</h3><p>demo-plan-${state.admin.planVersion} · 并发 1 · 固定规格</p>${button('发布并应用新演示权益','admin-plan')}<p class="hint">保留旧版本记录；此处不编辑真实权益。</p></section></div><section class="card section-gap"><h2>异常与长期冻结</h2>${state.tasks.filter(t=>['failed','reconciling','cancel_requested'].includes(t.status)).map(t=>`<div class="message"><strong>${M.statuses[t.status][0]}</strong> · ${t.reservation.state} · ${t.reservation.amount}<p class="task-meta">${t.id} · 更新 ${new Date(t.updatedAt).toLocaleString('zh-CN')}</p>${t.status==='reconciling'?button('依据模拟证据核对','admin-reconcile','',`data-id="${t.id}"`):'<p class="hint">不能任意覆盖任务终态。</p>'}</div>`).join('')||'<p class="muted">暂无异常任务。可在演示场景中载入“结果未知 / 长期冻结”。</p>'}</section><section class="card section-gap"><h2>操作审计 · 本地演示</h2>${state.admin.audit.map(a=>`<p>${esc(a.action)} · ${esc(a.reason)}<br><small>演示管理员 · ${new Date(a.at).toLocaleString('zh-CN')}</small></p>`).join('')||'<p class="muted">暂无操作记录</p>'}</section>`}`;}
function openModal(title,body,onSubmit){const d=$('#modal');modalReturn=focusIdentity(document.activeElement);d.innerHTML=`<form id="modal-form"><h2 id="dialog-title">${title}</h2>${body}<p id="modal-error" class="error" role="alert"></p><div class="row">${button('返回','close-modal')}<button class="primary" type="submit">确认</button></div></form>`;d.showModal();d.querySelector('input,textarea,select,button')?.focus();$('#modal-form').onsubmit=e=>{e.preventDefault();try{onSubmit(new FormData(e.target));d.close();save();render();notify('演示操作已完成。');}catch(err){$('#modal-error').textContent=err.message;}};}
$('#modal').addEventListener('close',()=>restoreFocus(modalReturn));
function setIntent(text,tool){if(blocked())return notify('请先恢复历史和原任务，再开始新的创作。');if(/翻唱|克隆|cover|clone/i.test(text))return notify('翻唱与声音克隆属于 P1，尚未开放，不会替换成其他收费工具。');let c=current();if(c.taskIds.length&&activeTask()?.reservation.state!=='held')c=M.createConversation(state);if(state.tasks.some(t=>t.conversationId===c.id&&t.reservation.state==='held'))return notify('本会话有未结束任务，请先查询原任务。');c.title=text.slice(0,18);c.messages.push({role:'user',text},{role:'assistant',text:'我理解了这个创作方向。请确认缺失参数，再查看工具提议。未确认前不会执行。'});c.intent=text;c.tool=tool||(text.includes('读')||text.includes('语音')||text.includes('TTS')?'speech.synthesize':text.includes('音乐')?'music.generate':'lyrics.generate');c.clarifying=true;c.editing=false;c.parameterDraft={text,language:'中文',style:'轻音乐'};c.lyricsAssetId=null;c.proposal=null;c.quote=null;c.draft='';save();render();}
function proposeFromAsset(a,tool){if(!M.accessible(a))return notify('作品已不可访问，请重新选择。');const c=M.createConversation(state);c.title=tool==='music.generate'?'从歌词到音乐':'AI 改写歌词';const input=tool==='music.generate'?{tool,prompt:'将选定歌词谱成温暖的轻音乐',specificationId:'demo-audio-8s',lyricsAssetId:a.id}:{tool,theme:'改写：'+a.textContent,language:'中文',style:'轻音乐'};M.proposal(c,tool,input);c.messages.push({role:'assistant',text:'已采用所选歌词内容 / 版本。下一步需要重新报价，并由你明确确认。'});page='workspace';save();render();}
function loadScenario(key){state=M.seed(M.fresh());state.logged=true;state.scenario=key;page='workspace';detailId=null;ledgerTask=null;ledgerCurrency='';filters={q:'',kind:'',tag:'',from:'',to:'',status:'accessible'};adminRole=false;const c=current();if(['normal','empty','loading','interrupted'].includes(key)){if(key==='interrupted')c.draft='请继续创作这首关于晚风的歌词';save();render();return;}M.proposal(c,'music.generate',{tool:'music.generate',prompt:'晚风与归途的轻音乐',specificationId:'demo-audio-8s'});M.quote(state,c);if(key==='insufficient')M.entry(state,'creation','adjustment','-119','0',null,'场景辅助：将可用余额调整为 1');if(key==='expired')c.quote.expiresAt=new Date(Date.now()-1000).toISOString();if(!['confirm','insufficient','expired'].includes(key)){const t=M.confirm(state,c);if(key!=='queued')M.transition(state,t,'running');if(['succeeded','failed','cancel_requested','reconciling'].includes(key))M.transition(state,t,key);if(key==='canceled'){M.transition(state,t,'cancel_requested');M.transition(state,t,'canceled');}if(key==='real'){M.transition(state,t,'succeeded');t.sourceMode='real';}if(key==='unsupported'){t.cancelSupported=false;t.allowedActions=[];}if(key==='reconciling')t.updatedAt=new Date(Date.now()-86400000).toISOString();}save();render();notify('已载入独立场景：'+scenarios[key]);}
const handlers={
 'admin-demo':()=>go('admin'),
 'auth-login':()=>{authAttempt++;busy=false;authMode='login';render();$('.auth-mode-icon')?.focus();},'auth-register':()=>{authAttempt++;busy=false;authMode='register';render();$('.auth-mode-icon')?.focus();},logout:()=>{state.logged=false;adminRole=false;save();render();},
 new:()=>{M.createConversation(state);save();render();},create:()=>{M.createConversation(state);go('workspace');},conversation:b=>{state.active=b.dataset.id;save();render();},
 'example-lyrics':()=>setIntent('写一首关于晚风与归途的歌','lyrics.generate'),'example-music':()=>setIntent('生成一段温暖的轻音乐','music.generate'),'example-tts':()=>setIntent('把“晚风来了，今天也辛苦了”读出来','speech.synthesize'),
 quote:()=>{M.quote(state,current());save();render();notify('报价已更新；尚未执行。');},
 confirm:()=>{try{const t=M.confirm(state,current());save();render();notify('已创建唯一模拟任务并冻结额度：'+t.id);}catch(e){notify(({QUOTE_EXPIRED:'报价已过期，请重新报价确认。',INSUFFICIENT_CREDITS:'余额不足，未创建任务。',CONCURRENCY_LIMIT:'演示并发上限为 1，请先查询已有任务。',FORBIDDEN:'演示账户已停用，无法创建任务。',PROVIDER_UNAVAILABLE:'演示工具已停用，请恢复配置后重新报价。',RESOURCE_NOT_FOUND:'引用的歌词已删除或不可访问，未创建任务；请重新选择作品。'})[e.message]||e.message);render();}},
 'edit-proposal':()=>{const c=current(),p=c.proposal;c.clarifying=true;c.editing=true;c.intent=p.tool==='music.generate'?(c.parameterDraft?.text||p.input.prompt):(p.input.theme||p.input.text);c.tool=p.tool;c.parameterDraft={text:c.intent,language:p.input.language||c.parameterDraft?.language||'中文',style:p.input.style||c.parameterDraft?.style||'轻音乐'};c.quote=null;save();render();notify('旧报价已作废，请重新确认参数。');},
 advance:()=>{const t=activeTask();if(t.status==='queued'&&(!state.admin.userEnabled||!state.admin.toolEnabled))M.transition(state,t,'failed');else M.transition(state,t,{queued:'running',running:'succeeded',cancel_requested:'canceled'}[t.status]);save();render();notify('任务状态：'+M.statuses[t.status][0]);},
 cancel:()=>{const t=activeTask();if(!t.allowedActions.includes('cancel'))return;openModal('确认请求取消？','<p>排队任务可直接取消；运行中先请求取消，确认成功后才释放冻结额度。</p>',()=>M.transition(state,t,t.status==='queued'?'canceled':'cancel_requested'));},
 requote:()=>{const t=activeTask();if(!t.allowedActions.includes('requote'))return;const c=current();M.proposal(c,t.tool,structuredClone(t.input),t.id);M.quote(state,c);save();render();notify('新报价已准备，需再次确认。');},
 query:()=>notify('已读取原 taskId 的本地模拟快照；没有重新提交或新增冻结。'),
 'task-ledger':()=>{ledgerTask=activeTask().id;go('credits');},'all-ledger':()=>{ledgerTask=null;render();},
 result:()=>{detailId=activeTask().assetIds[0];page='library';save();render();},detail:b=>{detailId=b.dataset.id;render();},'back-library':()=>{detailId=null;render();},'finish-delete':b=>{state.assets=state.assets.filter(a=>!(a.id===b.dataset.id&&a.status==='deletion_pending'));save();render();notify('模拟清理完成，移除本地回执。');},'clear-filter':()=>{filters={q:'',kind:'',tag:'',from:'',to:'',status:'accessible'};render();$('#main')?.scrollTo(0,0);$('#main')?.focus({preventScroll:true});},
 'asset-ledger':b=>{ledgerTask=getAsset(b.dataset.id).taskId;go('credits');},'asset-conversation':b=>{state.active=getAsset(b.dataset.id).conversationId;go('workspace');},
 download:b=>{const a=getAsset(b.dataset.id);if(!a)return notify('作品不可访问。');const link=document.createElement('a');let blob;if(a.kind==='lyrics'){blob=URL.createObjectURL(new Blob([a.textContent],{type:'text/plain;charset=utf-8'}));link.href=blob;link.download='museflow-demo-lyrics.txt';}else{link.href=a.kind==='cover'?'assets/cover.svg':'assets/sample.wav';link.download=a.kind==='cover'?'museflow-original-cover.svg':'museflow-demo-tone.wav';}document.body.append(link);link.click();link.remove();if(blob)setTimeout(()=>URL.revokeObjectURL(blob),1000);notify('已请求下载本地样例文件；实际保存位置由浏览器决定。');},
 rename:b=>{const a=getAsset(b.dataset.id);openModal('重命名作品',`<label for="title">作品名称</label><input id="title" name="title" maxlength="60" value="${esc(a.title)}" required>`,f=>{if(!f.get('title').trim())throw Error('名称不能为空');a.title=f.get('title').trim();});},
 delete:b=>{const a=getAsset(b.dataset.id);openModal('删除作品？',`<p>将移除「${esc(a.title)}」的本地访问入口。保留任务与账务证据。原型不执行服务器文件清理。</p>`,()=>{M.deleteAsset(state,a.id);detailId=null;});},
 manual:b=>{const a=getAsset(b.dataset.id);openModal('人工编辑 · 保存新版本',`<p>不扣生成积分；已有音频不变。</p><label for="lyrics">歌词正文</label><textarea id="lyrics" name="text" required maxlength="5000">${esc(a.textContent)}</textarea>`,f=>{detailId=M.manualVersion(state,a.id,f.get('text')).id;});},
 rewrite:b=>proposeFromAsset(getAsset(b.dataset.id),'lyrics.generate'),'next-music':b=>proposeFromAsset(getAsset(b.dataset.id),'music.generate'),
 preference:b=>{const p=state.preferences;if(!p.enabled)return notify('个性化已关闭，不记录标签偏好。');p.tags=p.tags.includes(b.dataset.id)?p.tags.filter(t=>t!==b.dataset.id):[...p.tags,b.dataset.id];save();render();notify('模拟偏好已改变推荐排序。');},
 favorite:b=>{const p=state.preferences;if(!p.enabled)return;p.saved=p.saved.includes(b.dataset.id)?p.saved.filter(x=>x!==b.dataset.id):[...p.saved,b.dataset.id];save();render();notify('演示收藏已更新，匹配项优先展示。');},
 dislike:b=>{if(!state.preferences.enabled)return;state.preferences.hidden.push(b.dataset.id);save();render();notify('已在演示推荐中隐藏该灵感。');},
 'use-inspiration':b=>{const i=inspirations.find(x=>x.id===b.dataset.id);M.createConversation(state);page='workspace';setIntent(i.text);},
 'reset-preferences':()=>openModal('重置推荐偏好？','<p>清除演示标签、收藏和不感兴趣记录；保留作品和账本。</p>',()=>{state.preferences={enabled:state.preferences.enabled,tags:[],saved:[],hidden:[]};}),
 role:()=>{adminRole=!adminRole;render();notify('仅切换演示视图；无真实权限控制。');},
 scenario:()=>{const key=$('#scenario').value;openModal('载入演示场景？','<p>会替换本标签页的演示会话、作品、账本与偏好。</p>',()=>loadScenario(key));},
 reset:()=>openModal('重置全部演示数据？','<p>清除本标签页的本地样例并回到模拟登录。不会访问任何服务。</p>',()=>{state=M.seed(M.fresh());page='workspace';adminRole=false;detailId=null;ledgerTask=null;ledgerCurrency='';filters={q:'',kind:'',tag:'',from:'',to:'',status:'accessible'};}),
 recover:()=>{state.scenario='normal';save();render();notify('已恢复本地历史和原任务快照，未新建任务。');},'close-modal':()=>$('#modal').close()
};
function showAdmin(action,b){if(!adminRole)return;const title={'admin-user':'变更账户状态','admin-tool':'变更工具可用性','admin-credit':'调整演示额度','admin-price':'发布新价格版本','admin-plan':'发布并应用权益版本','admin-reconcile':'核对异常任务'}[action];openModal(title,`<p>模拟敏感操作，需要原因和明确确认。不会修改真实服务。</p>${action==='admin-credit'?'<label for="currency">积分类型</label><select id="currency" name="currency"><option value="creation">创作积分</option><option value="voice">语音积分</option></select><label for="delta">调整数量（整数，可负，不动用冻结额）</label><input id="delta" name="delta" inputmode="numeric" value="10" required>':''}${action==='admin-reconcile'?'<label for="evidence">模拟证据</label><select id="evidence" name="evidence"><option value="unknown">尚无证据：继续核对</option><option value="failed">demo-proof-failure：确认终止且无产物</option><option value="succeeded">demo-proof-delivery：找到并归档样例</option></select>':''}<label for="reason">操作原因</label><textarea id="reason" name="reason" required maxlength="300" aria-describedby="modal-error"></textarea>`,f=>{const reason=f.get('reason').trim();if(!reason)throw Error('必须填写操作原因');if(action==='admin-credit'){const delta=f.get('delta').trim();if(!/^-?\d{1,12}$/.test(delta))throw Error('请输入最多 12 位的整数');M.entry(state,f.get('currency'),'adjustment',delta,'0',null,reason);}if(action==='admin-user'){state.admin.userEnabled=!state.admin.userEnabled;if(!state.admin.userEnabled){for(const t of state.tasks.filter(t=>t.status==='queued')){t.error={code:'FORBIDDEN',message:'账户已停用，尚未派发。'};M.transition(state,t,'failed');}}}if(action==='admin-tool')state.admin.toolEnabled=!state.admin.toolEnabled;if(action==='admin-price')state.admin.priceVersion++;if(action==='admin-plan')state.admin.planVersion++;if(action==='admin-reconcile'){const t=state.tasks.find(t=>t.id===b.dataset.id);if(f.get('evidence')!=='unknown')M.transition(state,t,f.get('evidence'));}state.admin.audit.unshift({action:title,reason,at:M.now()});});}
document.addEventListener('click',e=>{const nav=e.target.closest('.nav a');if(nav){e.preventDefault();go(nav.hash.slice(1));return;}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const action=b.dataset.action;if(action.startsWith('admin-')&&action!=='admin-demo')showAdmin(action,b);else {try{if(blocked()&&['confirm','quote','requote'].includes(action))throw Error('请先恢复历史并查询原任务，不能重新付费提交。');handlers[action]?.(b);}catch(error){notify(error.message==='RESOURCE_NOT_FOUND'?'引用的作品已删除或不可访问，请重新选择作品。':error.message);}}});
document.addEventListener('submit',e=>{const f=e.target;if(f.id==='auth-form'){e.preventDefault();if(busy)return;const email=$('#email'),pass=$('#pass'),nickname=$('#nickname');const invalid=!email.validity.valid||!email.value.trim()?email:!pass.value.trim()?pass:authMode==='register'&&!nickname.value.trim()?nickname:null;if(invalid){invalid.setAttribute('aria-invalid','true');$('#auth-error').textContent='请填写有效的邮箱、密码'+(authMode==='register'?'和昵称。':'。');invalid.focus();return;}email.removeAttribute('aria-invalid');pass.removeAttribute('aria-invalid');nickname?.removeAttribute('aria-invalid');const address=email.value.trim().toLowerCase(),outcome=address==='disabled@example.test'?'disabled':address==='error@example.test'?'error':'ok';busy=true;const submit=f.querySelector('[type=submit]');submit.disabled=true;submit.textContent='正在进入…';const attempt=++authAttempt;setTimeout(()=>{if(attempt!==authAttempt)return;busy=false;if(outcome==='ok'){state.logged=true;save();render();notify('已进入模拟工作区。');}else{$('#auth-error').textContent=outcome==='disabled'?'账户已停用，请联系平台管理员；此提示仅为演示。':'提交失败，请检查输入并重试（模拟错误，不披露账户信息）。';submit.disabled=false;submit.textContent=authMode==='login'?'进入工作区 →':'创建工作区 →';}},450);}if(f.id==='intent-form'){e.preventDefault();const text=$('#intent').value.trim();if(text)setIntent(text);}if(f.id==='clarify'){
 e.preventDefault();const c=current(),tool=c.tool,text=$('#parameter-text').value.trim();
 if(!text){$('#parameter-error').textContent='创作内容不能为空。';$('#parameter-text').setAttribute('aria-invalid','true');$('#parameter-text').focus();return;}
 const language=$('#language').value,style=$('#style')?.value||'轻音乐';
 c.intent=text;c.parameterDraft={text,language,style};
 const input=tool==='lyrics.generate'?{tool,theme:text,language,style,structure:'主歌 + 副歌'}:tool==='music.generate'?{tool,prompt:text+' / '+language+' / '+style,specificationId:'demo-audio-8s'}:{tool,text,voiceRef:'demo:soft',language,specificationId:'demo-tts-default'};
 if(c.editing&&c.proposal?.input.lyricsAssetId)input.lyricsAssetId=c.proposal.input.lyricsAssetId;
 if(c.editing)M.editProposal(c,input);else M.proposal(c,tool,input);
 c.clarifying=false;c.editing=false;save();render();notify('参数已补齐；工具提议尚未执行。');
}if(f.id==='filters'){e.preventDefault();const from=$('#from').value,to=$('#to').value;if(from&&to&&from>to){$('#filter-error').textContent='结束日期不能早于起始日期。';return;}filters={q:$('#search').value.trim(),kind:$('#kind').value,tag:$('#tag').value,from,to,status:$('#asset-status').value};render();$('#main')?.scrollTo(0,0);$('#main')?.focus({preventScroll:true});}});
document.addEventListener('input',e=>{if(e.target.id==='intent'){current().draft=e.target.value;save();}if(e.target.closest('#clarify')){current().parameterDraft={text:$('#parameter-text').value,language:$('#language').value,style:$('#style')?.value||'轻音乐'};save();}});
document.addEventListener('change',e=>{if(e.target.id==='ledger-currency'){ledgerCurrency=e.target.value;render();}if(e.target.id==='personalization'){const enabled=e.target.checked;state.preferences.enabled=enabled;save();render();notify(enabled?'已开启演示个性化。':'已关闭个性化，停止记录推荐反馈。');}});
document.addEventListener('error',e=>{if(e.target.tagName==='AUDIO'||e.target.tagName==='SOURCE')notify('示例音频加载失败，请检查本地文件；没有伪造播放结果。');},true);
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(names[p])go(p);});
window.addEventListener('offline',()=>{if(state.logged){state.scenario='network';save();render();notify('网络异常：不将任务标为失败，请恢复后查询原任务。');}});
if(names[location.hash.slice(1)])page=location.hash.slice(1);render();
// Refresh visible expiry without replacing focused form controls.
setInterval(()=>{if(!state.logged||page!=='workspace')return;const q=current()?.quote;const b=document.querySelector('[data-action="confirm"]');if(q&&b&&Date.parse(q.expiresAt)<=Date.now()){render();notify('报价已过期，请重新报价并确认。');}},1000);
